version: "3.9"
services:
  app:
    build: .
    image: consulting_ai_assistant:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
